### ISSUE TITLE
'Glow' object has no attribute 'init_lstm_hidden'

### ISSUE THREAD

**Issue by Yuefengxin** [wenyh1616/StyleMotion#1]
Great job! But I got error "'Glow' object has no attribute 'init_lstm_hidden'" when running the code. Is the code partially missing? Hope to get your reply, thanks!

Traceback (most recent call last):
  File "train.py", line 51, in <module>
    trainer.train()
  File "StyleMotion/glow/trainer.py", line 389, in train
    self.graph.init_lstm_hidden()
  File "anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'Glow' object has no attribute 'init_lstm_hidden'

**Comment by ktxu1224** [comment]
@Yuefengxin Hi, have you solved this problem?
